# Generated by Django 5.1.5 on 2025-04-14 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(default='000000000000', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account_holder',
            field=models.CharField(default='Company Account', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(default='XYZ Bank', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='base_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.CharField(default='Main Branch', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_gst',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consignee_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consignee_gst',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consignee_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_note_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='destination',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='gst_consultancy',
            field=models.CharField(default='Consultancy', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hsn_code',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ifsc_code',
            field=models.CharField(default='XYZB0000000', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='INV-0001', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remark',
            field=models.TextField(default='No remarks'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_email',
            field=models.EmailField(default='noemail@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_gstin',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_pan',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sgst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='swift_code',
            field=models.CharField(default='XYZ000', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_with_gst',
            field=models.FloatField(default=0.0),
        ),
    ]
