# Generated by Django 5.1.5 on 2025-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0002_remove_invoice_customer_name_remove_invoice_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(default='Unknown', max_length=255)),
                ('seller_address', models.TextField(default='Not Provided')),
                ('seller_email', models.EmailField(default='noemail@example.com', max_length=254)),
                ('seller_pan', models.CharField(default='UNKNOWN', max_length=20)),
                ('seller_gstin', models.CharField(default='UNKNOWN', max_length=20)),
                ('bank_account_holder', models.CharField(default='Company Account', max_length=255)),
                ('bank_name', models.CharField(default='XYZ Bank', max_length=255)),
                ('account_number', models.CharField(default='000000000000', max_length=50)),
                ('ifsc_code', models.CharField(default='XYZB0000000', max_length=20)),
                ('branch', models.CharField(default='Main Branch', max_length=255)),
                ('swift_code', models.CharField(default='XYZ000', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='INV-0001', max_length=20, unique=True),
        ),
    ]
