# Generated by Django 5.1.5 on 2025-04-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0005_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='gst_consultancy',
            new_name='Particulars',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Terms_to_delivery',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
