# Generated by Django 5.1.5 on 2025-04-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0007_alter_setting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
