# Generated by Django 5.1.5 on 2025-04-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0008_invoice_taxtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='financial_year',
            field=models.CharField(default='2025-2026', max_length=9),
        ),
    ]
