# Generated by Django 5.1.5 on 2025-04-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0011_remove_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='01-2025/2026', max_length=20),
        ),
    ]
