# Generated by Django 5.2 on 2025-04-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0013_invoice_amount_in_words_statement_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255)),
                ('invoice_id', models.CharField(max_length=50)),
                ('selected_date', models.DateField()),
                ('notice', models.TextField()),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_date', models.DateField()),
                ('company_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notice', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_date', models.DateField()),
                ('other_notice', models.TextField()),
                ('other_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_name', models.CharField(max_length=255)),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='last_invoice_number',
            field=models.IntegerField(default=0),
        ),
    ]
