# Generated by Django 5.2 on 2025-04-30 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0016_remove_buyer_buyer_name_remove_buyer_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='buyer_name',
            field=models.CharField(default='UNKNOWN', max_length=255),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='invoice_id',
            field=models.CharField(default='01-2025/2026', max_length=50),
        ),
        migrations.AlterField(
            model_name='companybill',
            name='selected_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
