# Generated by Django 5.2 on 2025-05-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0020_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='company_name',
            field=models.CharField(default='Company name', max_length=255),
        ),
    ]
