# Generated by Django 5.2 on 2025-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0021_setting_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='companybill',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
