# Generated by Django 5.2 on 2025-05-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0022_remove_buyer_invoice_id_companybill_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companybill',
            name='bill_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
