# Generated by Django 5.1.5 on 2025-04-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0003_setting_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bank_account_holder',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_gstin',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='seller_pan',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='swift_code',
        ),
    ]
