# Generated by Django 5.1.5 on 2025-04-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0004_remove_invoice_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='INV-0001', max_length=20),
        ),
    ]
