# Generated by Django 5.1.5 on 2025-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0009_invoice_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20),
        ),
    ]
