# Generated by Django 5.2 on 2025-04-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_backend', '0015_salary_salary_newname_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='selected_date',
        ),
        migrations.RemoveField(
            model_name='companybill',
            name='company_amount',
        ),
        migrations.RemoveField(
            model_name='companybill',
            name='company_date',
        ),
        migrations.RemoveField(
            model_name='companybill',
            name='company_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='company_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='buyer',
            name='company_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companybill',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companybill',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companybill',
            name='invoice_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companybill',
            name='selected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
